added LoginViewModel validation
wolox-training/ei-android pull request #2
Opened 2022-09-27 20:49 UTC by EstebanIndiveri

Added LoginViewModel
Added navigation
Added email and password observe

[validations.webm](https://user-images.githubusercontent.com/54692138/192632405-57676fe0-a451-4675-be0a-0004ef5249c4.webm)

2022-09-28 14:09 UTC, Marcosnr97 commented on app/src/main/java/com/example/woloxapp/ui/Home/HomeFragment.kt
> +        val buttonPrimary = binding.buttonPrimary
You dont neccesarily need to assign a val here.
You could use `with(binding) { }` and assign the listeners there

2022-09-28 14:09 UTC, Marcosnr97 commented on app/src/main/java/com/example/woloxapp/ui/login/LoginFragment.kt
> +    companion object {
companion objects usually go on the bottom of the class
https://kotlinlang.org/docs/coding-conventions.html#class-layout

2022-09-28 14:09 UTC, Marcosnr97 commented on app/src/main/res/layout/fragment_homescreen.xml
> +        tools:layout_editor_absoluteX="16dp" />
check dp and sp values on this file, move this values to the dimen file

2022-09-28 14:09 UTC, LisandroDiMeo commented on app/src/main/java/com/example/woloxapp/ui/Home/HomeFragment.kt
> +            if (::loginViewModel.isInitialized) {
why this logic ?

2022-09-28 14:16 UTC, LisandroDiMeo commented on app/src/main/java/com/example/woloxapp/ui/login/LoginViewModel.kt
> +class LoginViewModel(private val applicationCustom: Application) : AndroidViewModel(applicationCustom) {
I think applicationCustom is not a very declarative name

2022-09-28 14:21 UTC, LisandroDiMeo commented on app/src/main/java/com/example/woloxapp/ui/login/LoginViewModel.kt
> +        const val SHARED_PREFERENCES_USERNAME: String = R.string.shared_preferences_username.toString()
be careful with this, since accessing to resources retrieves an id representing such string. After this, you should obtain it using the context

2022-09-28 14:22 UTC, LisandroDiMeo commented on app/src/main/java/com/example/woloxapp/ui/login/LoginViewModel.kt
> +    private val sharedPreferencesSaved: SharedPreferences = applicationCustom.applicationContext.getSharedPreferences(
```
SharedPreferences sharedPref = context.getSharedPreferences(
        getString(R.string.preference_file_key), Context.MODE_PRIVATE);
```

2022-09-28 14:30 UTC, LisandroDiMeo commented on app/src/main/java/com/example/woloxapp/ui/login/LoginViewModel.kt
> +        val valid = emailValue.isEmpty() || passwordValue.isEmpty()
this is kinda ambiguous, you're referring as _valid_ a situation where the email is empty or the password is empty

2022-09-28 14:33 UTC, LisandroDiMeo commented on app/src/main/java/com/example/woloxapp/ui/login/LoginViewModel.kt
> +        const val SHARED_PREFERENCES_USERNAME: String = R.string.shared_preferences_username.toString()
To clarify, R.string.username.toString() is something like "948172". If you want to have a reference to sharedPreferences keys, its not necessary to use the string resources path (moreover, its not recommended). The string resources path should be used only for UI related stuff. In this case, you may simply declare the string you prefer

2022-09-28 14:36 UTC, LisandroDiMeo commented on app/src/main/java/com/example/woloxapp/ui/login/LoginFragment.kt
> +            if (it == true) {
this is okay, but keep in mind that when you add real credentials validation this should change

2022-09-28 14:40 UTC, LisandroDiMeo requested changes
Good progress! Just a few changes to improve

2022-09-30 13:45 UTC, LisandroDiMeo approved these changes

2022-09-30 14:06 UTC, Marcosnr97 approved these changes

2022-09-30 14:30 UTC, jcruz-wolox approved these changes

2022-10-11 15:59 UTC, merged